version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres-docker
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=library
        - POSTGRES_HOST=pg_host
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    container_name: es01
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
  # pgadmin:
  #     container_name: pgadmin4_container
  #     image: dpage/pgadmin4
  #     restart: always
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: emmanuelzakaryan@gmail.com
  #       PGADMIN_DEFAULT_PASSWORD: postgres
  #     ports:
  #       - "5050:80"

volumes:
  pgdata:
  elastic_data: